#!/bin/sh

# Super+Shift+Escape to exit river
riverctl map normal Super+Shift Escape exit

### MENUS ###

riverctl map normal Super A spawn fuzzel
riverctl map normal Super+Shift A spawn "fuzzel --list-executables-in-path"
riverctl map normal Super Escape spawn menusys
riverctl map normal Super N spawn menunm
riverctl map normal Super B spawn menubt
riverctl map normal Super V spawn menuclip
riverctl map normal Super S spawn menushot

### VIEWS ###

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super Return spawn foot

# Super+Shift+T to start an instance of tmux in foot
riverctl map normal Super T spawn "foot tmux"

# Super+Shift+W to start an instance of alternative browser; firefox
riverctl map normal Super+Shift W spawn firefox

### STACK ###

# Super+F to toggle float
riverctl map normal Super F toggle-float

# Super+X to toggle fullscreen
riverctl map normal Super X toggle-fullscreen

# Super+Z to bump the focused view to the top of the layout stack
riverctl map normal Super Z zoom

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+H and Super+L to decrease/increase the main ratio of wideriver(1)
riverctl map normal Super H send-layout-cmd wideriver "--ratio -0.05"
riverctl map normal Super L send-layout-cmd wideriver "--ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of wideriver(1)
riverctl map normal Super+Shift H send-layout-cmd wideriver "--count +1"
riverctl map normal Super+Shift L send-layout-cmd wideriver "--count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Wideriver layout switching
riverctl map normal Super N send-layout-cmd wideriver "--layout top"
riverctl map normal Super M send-layout-cmd wideriver "--layout monocle"
riverctl map normal Super Comma send-layout-cmd wideriver "--layout left"
riverctl map normal Super Period send-layout-cmd wideriver "--layout right"
riverctl map normal Super Slash send-layout-cmd wideriver "--layout wide"

### TAGS ###

for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  # Super+[1-9] to focus tag [0-8]
  riverctl map normal Super $i set-focused-tags $tags

  # Super+Shift+[1-9] to tag focused view with tag [0-8]
  riverctl map normal Super+Shift $i set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control $i toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

### OUTPUTS ###

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super BracketRight focus-output next
riverctl map normal Super BracketLeft focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift BracketRight send-to-output next
riverctl map normal Super+Shift BracketLeft send-to-output previous

### MEDIA KEYS ###

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do

  riverctl map $mode None XF86AudioRaiseVolume spawn 'tctl audio up'
  riverctl map $mode None XF86AudioLowerVolume spawn 'tctl audio down'
  riverctl map $mode None XF86AudioMute spawn 'tctl audio mute'
  riverctl map $mode None XF86AudioMicMute spawn 'tctl audio micmute'

  riverctl map $mode None  XF86MonBrightnessUp spawn 'tctl brightness up'
  riverctl map $mode None  XF86MonBrightnessDown spawn 'tctl brightness down'
  riverctl map $mode Shift XF86MonBrightnessUp spawn 'tctl brightness keyup'
  riverctl map $mode Shift XF86MonBrightnessDown spawn 'tctl brightness keydown'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext spawn 'playerctl next'

done


