#! /bin/sh

${XDG_CONFIG_HOME}/river/init.d/appearance &
${XDG_CONFIG_HOME}/river/init.d/autostart &
${XDG_CONFIG_HOME}/river/init.d/behaviour &
${XDG_CONFIG_HOME}/river/init.d/input &
${XDG_CONFIG_HOME}/river/init.d/keymap &
${XDG_CONFIG_HOME}/river/init.d/layout &
