[general]
live_config_reload = true
import = ["~/.config/alacritty/gruvbox-flat.toml"]

[font]
size = 11

[font.normal]
family = "FiraCode Nerd Font Mono"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "linkhandler"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi|~Search"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 14
y = 4
