# gruvbox Alacritty Colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black = '#1D2021'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

# Bright colors
[colors.bright]
black = '#17191a'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

[[colors.indexed_colors]]
index = 16
color = '#1d2021'

[[colors.indexed_colors]]
index = 17
color = '#c14a4a'
